### ISSUE TITLE
Custom GWEN skin issues

### ISSUE THREAD

**Issue by Mors-Quaedam** [Nayruden/Ulysses#192]
Not that this is a high priority issue, it's little things that can matter too. When choosing a custom GWEN skin for the XGUI, certain elements do not use the 'new' skin. 
This mainly happens in the Cmds menu when selecting a command.

http://puu.sh/2vNQU/f250271884

There, the all the controls in the "ulx ban" menu are using the default GWEN skin, whereas the rest of the XGUI is using the custom one.

Again, not a high priority but it's something that should be put out there.

**Comment by SticklyMan** [comment]
Finally got around to fixing this. 8b4f4a34f8831cecedda90f503048de766b8d986

There are still a few issues with text in some areas with certain skins, but I can't tell if it's caused by poorly programmed skins or incorrect configuration in XGUI. I will ignore the issue for now unless it comes up. If it does, I'll want a sample of the problematic skins in question.
