### ISSUE TITLE
ulx map "restrict gamemode"

### ISSUE THREAD

**Issue by chaos12135** [Nayruden/Ulysses#400]
In 
Cmds > Utility > Map
The gamemode restriction will work, but when you go to the "Maps" tab, the gamemode restriction no longer works. I'm going to assume the same happens to maps that are restricted.

**Comment by SticklyMan** [comment]
Fixed in fb68a566db45f211d0aa808e73dd7a2b6f64f4a7. Thanks for the heads up!

The "maps" tab has multiple functions, and the current UI flow does not allow me to easily only display valid maps for 'ulx map' when I also have to take into account votemaps and other things. So, I probably won't be getting a fix implemented anytime soon. At least, ULX won't let you change to a map you aren't allowed to, so it's not a pressing issue.
