### ISSUE TITLE
[ULX] Conflict with another addon

### ISSUE THREAD

**Issue by Bryantdl7** [Nayruden/Ulysses#415]
Lua Error: [ERROR] addons/buildmode/lua/autorun/buildmode.lua:68: attempt to call method 'GetNetworkedVar' (a nil value) 1. fn - addons/buildmode/lua/autorun/buildmode.lua:68 2. unknown - addons/ulib/lua/ulib/shared/hook.lua:184

It seems like it's blaming ulib, if not correct me and I will go after the addon maker.

**Comment by SticklyMan** [comment]
NetworkedVars were recently changed in the latest Garry's Mod update, and it's likely that addon needs to be fixed for the new update.

ULib is only showing up in this case because we override the default hook library to add support for hook prioritization, something that has been thoroughly discussed and is not known to create any problems.
