### ISSUE TITLE
Hide ULX used commands

### ISSUE THREAD

**Issue by PwndKilled** [Nayruden/Ulysses#428]
I'd like you to add a way to hide the ULX used commands.

ulx_hidecommandonchat 1

Exemple: 
I type !bring PwndKilled

Chat:
!bring PwndKilled (to be hide)
You brought PwndKilled

I want command to be hidden on the chat. (to not appear)

Sincerely,

**Comment by edgarasf123** [comment]
ulx_logecho 0

**Comment by Nayruden** [comment]
To hide commands, set logecho to 0 (as @edgarasf123  suggested) and use the console instead of chat.

**Comment by PwndKilled** [comment]
I only use chat, and ulx_logecho is already set to 0...
So why close it when it's not even fixed?

**Comment by Nayruden** [comment]
Because it's not something we're going to change.

**Comment by PwndKilled** [comment]
I never said change but add an option to do it...
I said something like this
local function OnPlayerChat( ply, strText, bTeamOnly, bPlayerIsDead ) 
    if strText[1] == "!" then 
        return true 
    end
end
hook.Add( "OnPlayerChat", "testhook", OnPlayerChat )

**Comment by SticklyMan** [comment]
Like Megiddo said, use console commands instead of chat to keep things hidden. Hiding chat commands by default could potentially break other addons that rely on chat commands.

However, if you want to implement it anyways, you can go right ahead. If you want ALL chat commands to be hidden, go to ULib's commands.lua, find the addCommand function, and add a line to force the hide_say parameter to always be true.
https://github.com/Nayruden/Ulysses/blob/master/ulib/lua/ulib/shared/commands.lua#L1418

If you only want to hide specific commands, you'll need to find each addCommand and set the hide_say parameter to true (or add it).
https://github.com/Nayruden/Ulysses/blob/master/ulx/lua/ulx/modules/sh/fun.lua#L20

**Comment by PwndKilled** [comment]
Alright, thanks.
How could it break others addons that rely on chat commands ?

**Comment by edgarasf123** [comment]
Because returning "" will not run any other PlayerSay hooks.
