### ISSUE TITLE
Ban error

### ISSUE THREAD

**Issue by BCBEST** [Nayruden/Ulysses#442]
Under the ban list, nothing shows up and if I search I get:

[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:395: bad argument #1 to 'pairs' (table expected, got number)
  1. pairs - [C]:-1
   2. populateBans - addons/ulx/lua/ulx/xgui/bans.lua:395
    3. OnValueChange - addons/ulx/lua/ulx/xgui/bans.lua:35
     4. OnEnter - lua/vgui/dtextentry.lua:259
      5. unknown - lua/vgui/dtextentry.lua:104

**Comment by Nayruden** [comment]
@BCBEST, are you still having this issue?

**Comment by BCBEST** [comment]
Yes.

**Comment by SticklyMan** [comment]
Sincere apologies for the delay in looking into this. It appears you are running a very old version of ULX/XGUI, based on the error. (Somewhere between Aug 2013-2014) Have you tried updating with our latest version here on GitHub, or our latest release on our downloads page? Do this if you can, then let us know if it helped. http://ulyssesmod.net/downloads.php

You might also have an old copy of bans.lua if it has been customized for Sourcebans or SQL integration. If this is the case, you will likely want to check for updates with whatever system you used, as we cannot provide any further help.

For now, I will be closing this issue since it does not seem to be a widespread issue. Feel free to post any additional findings here, or email us at team@ulyssesmod.net or post on our forums at http://forums.ulyssesmod.net if you need further assistance.

Hope this helps!
