### ISSUE TITLE
New priority scheme versus legacy read only priorities

### ISSUE THREAD

**Issue by ascentechit** [Nayruden/Ulysses#448]
Won't the new priority scheme and the clamping that's being done create problems with old hook priorities?  For example..

Say I have a hook for CanTool with a priority of -10.  Under the old priority scheme, this was NOT a read-only hook, and my function can return a value that is honored by the CanTool hook chain.
The new ULib rehooking will clamp this -10 to -2. Under the new scheme, -2 is a read-only priority.  This means that the return value from my CanTool hook will be ignored.

Doesn't this create a pretty big legacy issue? Wouldn't something like the following in shared/hook.lua help eliminate the issue?

	if ( priority == -20 ) then priority = -2 end 
	if ( priority == 20 ) then priority = 2 end
	
	if ( priority < -2 ) then priority = -1 end -- math.Clamp may not have been defined yet
	if ( priority > 2 ) then priority = 1 end

**Comment by darkjacky** [comment]
local priority = priority <= -20 and -2 or priority >= 20 and 2 or priority < -2 and -1 or priority > 2 and 1 or priority or 0

is the quickest way.
But they want to have the hook module integrated into Gmod itself. if that happens there is always going to be incompatibilities. Just deal with it by editing its not a big problem.

The thing I am wondering is why bother having a monitor at all. If you don't want to interrupt the hook then return nil. simple.

**Comment by ascentechit** [comment]
I was going for clarity here, not raw performance.  It would appear the new approach creates the potential for a lot of headaches with legacy hook priorities.  Saying it's not a big problem doesn't make it not a big problem.  Personally I don't want to have to review and debug dozens of scripts if there's a relatively simple way to make the new approach more backwards compatible with existing priorities and their intentions.

**Comment by ascentechit** [comment]
^^^ If my above seemed snippy, my apologies.  I was coming off an 18 hr day and was a bit out of it when I penned it.

Anyway, I can see the value of a monitor priority from the perspective of always being able to enter the hook chain before (or after) everything else is done, especially if the goal is truly to monitor (think timers for DBugr and other projects like that).

**Comment by Nayruden** [comment]
@ascentechit, I would have normally implemented something like you posted
for a breaking change like this, but we decided the situation was unique
enough to not need it. All existing mods will still hook properly, at worst
they won't be able to return a value. It should be pretty clear what the
issue is, and will not break in any horrible way. That, combined with the
fact that we are submitting the hooks for inclusion into GMod proper drove
the decision to make the breaking change.

@darkjacky, you're missing the point. Read only hooks don't protect
developers from themselves, they protect developers from other developers.
I initially made the ULib hook system for this very reason -- I was tired
of ULib/ULX breaking because server admins were running mods written by ten
year olds with no understanding of what happens when they return a value
from a hook. By creating a high priority read only hook, you are guaranteed
that your hook WILL be called, regardless of what else is going on in the
server.

**Comment by ascentechit** [comment]
>> Read only hooks don't protect developers from themselves, they protect developers from other developers.

Amen to that.  :)

**Comment by darkjacky** [comment]
Sure. But then the readonly low is useless? (prio +2) So then remove it?

**Comment by Nayruden** [comment]
It's not useless. It lets you know that an action is being allowed. E.G.,
if you want to know when a player spawns a prop, you can use readonly low.
Any other hook priority and it's possible it may be blocked after you
receive the event. Gotta think outside the box, @darkjacky. ;)

**Comment by darkjacky** [comment]
So that after that the gamemode can block it? :P It still does not look very useful to me. But that does not matter.

**Comment by ascentechit** [comment]
Let's say there are 3 hooks with priority +1.  You can't guarantee which ones will run, so if you have a hook at +1 then it's entirely likely the chain can get stopped *after* your hook processed.  At +2, that's not going to happen.
