### ISSUE TITLE
Groups not being delted

### ISSUE THREAD

**Issue by MrUnknownGamer** [Nayruden/Ulysses#451]
Hi,

I am deleting ULX groups and when I do, they seem to be removed, though when doing a map change or doing a _restart, the groups are back and I am readed by to the group I was in before

**Comment by YourStalker** [comment]
Does this also happen when promoting players? What OS are you on?

**Comment by MrUnknownGamer** [comment]
I was on Windows, I just switched to a 30 slot Linux server. Ill see what happens

**Comment by YourStalker** [comment]
Check your data folder and see if the ulib group files are being modified after you delete groups and change maps. If the text file does change then it's because you don't own it in linux (had this issue myself). Simply as root run this

"chown user /path/to/garrysmodserver -R"

In the user spot put the user that's running srcds.

**Comment by Nayruden** [comment]
Not a Ulysses-controllable issue. Most likely a permission problem.
