### ISSUE TITLE
Votemap list gets inverted

### ISSUE THREAD

**Issue by Mates** [Nayruden/Ulysses#500]
I have votemap set to only use the specified maps (votemapMapmode 2). When I set the allowed maps, everything works fine until the server is restarted. Right after the first player starts joining, the content of votemaps.txt gets inverted - original maps are removed and all other maps are added, making those allowed and the original ones excluded. This is probably the same issue as #335

**Comment by SticklyMan** [comment]
Is this still an issue that's happening to you? Does it happen very frequently? We still have not been able to replicate this issue, but it has been reported a few times.

Could you send us your data\ulx\config.txt and data\ulx\votemaps.txt files so we can take a preliminary look? Which gamemode and addons are you running?

Otherwise, would it be possible for us to hop on your server and take a look ourselves? We can't make a fix if we can't first figure out what's causing the issue.

**Comment by Mates** [comment]
I've disabled votemap for the time being, but I will re-enable it, try if it still happens and send the files in the next few days, hopefully. I've only tried on sandbox so far, but I can try on other gamemodes as well. I'll also try on a clean server with no other addons to make sure.

**Comment by SticklyMan** [comment]
Thanks for your help- Sandbox is actually preferred, so there's no need to test other gamemodes. The best way for us to fix the issue would be to hop on your server and see it in action, so do keep me posted on your findings. If you'd like, you can add me on Steam here for quicker communication: http://steamcommunity.com/id/Stickly_Man/

**Comment by SticklyMan** [comment]
Thanks for letting me test on your server- it was very helpful! This has been fixed in: 
https://github.com/TeamUlysses/ulx/commit/9a5ab02972dcfe26234f2a3e47afb3008ec1571d

We are moving repositories- see here for more details:
http://forums.ulyssesmod.net/index.php/topic,9111.0.html
