### ISSUE TITLE
Error when registering new privilege with CAMI.RegisterPrivilege

### ISSUE THREAD

**Issue by Mates** [Nayruden/Ulysses#504]
When trying to register new privilege using CAMI.RegisterPrivilege like so
```
CAMI.RegisterPrivilege{
	Name = "some_new_privilege",
	MinAccess = "admin"
}
```
the following error occurs
```
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: This group (user) cannot have it's inheritance changed!
  1. setGroupInheritance - [C]:-1
   2. fn - addons/ulib/lua/ulib/server/cami.lua:22
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:110
     4. RegisterUsergroup - lua/sh_cami.lua:88
      5. unknown - lua/sh_cami.lua:93
       6. include - [C]:-1
        7. unknown - lua/autorun/server/usergroup_check.lua:17
```

**Comment by deinemudda32** [comment]
Happens on server start on my server.

**Comment by Nayruden** [comment]
Odd, I ran a few tests while working on it last night and it ran fine. Testing again now.

**Comment by Nayruden** [comment]
Confirmed: Not an issue with CAMI+ULib. Based on the stack trace, something legitimately is trying to change the inheritance of the "user" group. What is usergroup_check.lua?

**Comment by Mates** [comment]
Huh, weird. usergroup_check.lua is my own script that is supposed to change the usergroup of user if it differs from the one stored in MySQL database (basically sync the usergroup with DB), but it shouldn't touch inheritance in any way. I'll try to write some very basic test script and go from there.

**Comment by deinemudda32** [comment]
It does a lua error in my case on starting server.

**Comment by Nayruden** [comment]
Please give more detail, @deinemudda32. You would not be receiving the same error unless you're running the same script @Mates is.

**Comment by Nayruden** [comment]
@Mates, CAMI spec is that you should not call usergroup registered for the default groups (user, admin, superadmin). Even if you're not trying to change inheritance, that's the root problem.

**Comment by deinemudda32** [comment]
I updated ULX and DarkRP(yea im Running DarkRP) both at the same time.
Since this moment everytime I start my server this error occurs.

[ERROR] addons/ulx/lua/ulib/shared/hook.lua:110: This group (user) cannot have it's inheritance changed!
  1. setGroupInheritance - [C]:-1
   2. fn - addons/ulx/lua/ulib/server/cami.lua:22
    3. Call - addons/ulx/lua/ulib/shared/hook.lua:110
     4. RegisterUsergroup - gamemodes/darkrp/gamemode/libraries/sh_cami.lua:88
      5. unknown - gamemodes/darkrp/gamemode/libraries/sh_cami.lua:93
       6. include - [C]:-1
        7. unknown - gamemodes/darkrp/gamemode/init.lua:34

**Comment by Mates** [comment]
@Nayruden I'm not calling usergroup registered anywhere, so that's even weirder. I'll try to track it down.

**Comment by Nayruden** [comment]
Actually @Mates, I think this is just an issue of having more than one CAMI library on a server. The ULib one is getting loaded first, then the ULib supporting functions, then the DarkRP version of CAMI. Thus, @FPtje is breaking his own spec in an interesting way. I've linked him in to the discussion. But, the change I just pushed will fix it either way.

@FPtje: To be more specific, this is a problem because other addons are not expecting usergroupRegistered to be called for the default groups, but because ULib is already fully good to go, the next load of CAMI (though it has to be a newer version to pass the file conditional) re-registers the default groups. To fix this, I'd suggest loading the default groups directly into the table and circumvent the callbacks, or add a conditional to see if CAMI has been loaded (even an older version) already.

**Comment by Nayruden** [comment]
@deinemudda32, that means if you update it should be fixed for you too.

**Comment by Mates** [comment]
@Nayruden Yep, seems like it. I just tried this minimalistic approach (test.lua):
```
include("sh_cami.lua")

CAMI.RegisterPrivilege{
	Name = "some_privilege",
	MinAccess = "superadmin"
}
```
and the same error
```
[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: This group (user) cannot have it's inheritance changed!
  1. setGroupInheritance - [C]:-1
   2. fn - addons/ulib/lua/ulib/server/cami.lua:22
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:110
     4. RegisterUsergroup - lua/sh_cami.lua:88
      5. unknown - lua/sh_cami.lua:93
       6. include - [C]:-1
        7. unknown - lua/autorun/server/test.lua:1


[ERROR] addons/ulib/lua/ulib/shared/hook.lua:110: This group (user) cannot have it's inheritance changed!
  1. setGroupInheritance - [C]:-1
   2. fn - addons/ulib/lua/ulib/server/cami.lua:22
    3. Call - addons/ulib/lua/ulib/shared/hook.lua:110
     4. RegisterUsergroup - lua/sh_cami.lua:88
      5. unknown - lua/sh_cami.lua:93
       6. include - [C]:-1
        7. unknown - lua/autorun/server/test.lua:1

```

**Comment by FPtje** [comment]
Just a side note here, but could you please change the "it's" grammar error? It irks me D:

**Comment by Nayruden** [comment]
Thanks, @FPtje!
