### ISSUE TITLE
Bans/kicks and some commands not effective after a moment

### ISSUE THREAD

**Issue by Cipio1106** [Nayruden/Ulysses#519]
Hello,

After a little moment (it's variable), the staff can't ban/kick/jail/etc. players normally.
The commands are not  displayed in chat and the ban is not writed into database.
And the server display an error :

"[ERROR] Unauthed player
  1. query - [C]:-1
   2. calcSlots - addons/ulx/lua/ulx/modules/slots.lua:20
    3. fn - addons/ulx/lua/ulx/modules/slots.lua:52
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. probe - addons/ulib/lua/ulib/server/ucl.lua:948
       6. fn - addons/ulib/lua/ulib/server/ucl.lua:1014
        7. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
         8. UniqueID - [C]:-1
          9. echoToAdmins - addons/ulx/lua/ulx/log.lua:164
           10. fn - addons/ulx/lua/ulx/log.lua:202
            11. unknown - addons/ulib/lua/ulib/shared/hook.lua:110"

So, I pasted it on Google and found many results :

http://forums.ulyssesmod.net/index.php?topic=4425.0

I'm under Linux, my ULX/Ulib version is up to date, Gmod is up to date, DarkRP is up to date.
And I tried many times to remove completely, reinstall, clear data, etc.
No result, bug persists.

Oh, and I'm using Ulx Global Ban from bcool...I don't know if it's the problem source, but I think not :
https://github.com/bcool/ULX-Global-Ban

Please, help me...this bug is bloody.
Have a nice day !

**Comment by eGolono** [comment]
I don't mean to butt in but rather than creating a new issue report I thought that I'd just add that I'm experiencing a similar problem on my TTT server. Admins are unable to slay any players next round and receive the "Player will not be slayed next round." message in chat. This is specifically with the slaynr command, the slay command works fine. 

We've tried all of the mediums available to issue the command such as the console, chat shortcuts, and through the damage logs addon to no avail. This has specifically become a problem since the last update to Garry's Mod.

**Comment by Cipio1106** [comment]
Hi,

I don't think it's last update from Garry's Mod. This bug persists since 3-4 months for me, I tried every possible solution (restart, reinstall, delete data, remove others add-ons, reinstall one by one, etc) 

So now I report this problem to dev because I dont have any idea :/

**Comment by Nayruden** [comment]
#366 is related. Not sure what the ultimate cause is, but I'm writing a quick fix so it won't error at this spot, at least.
