### ISSUE TITLE
Weird message after update

### ISSUE THREAD

**Issue by deinemudda32** [Nayruden/Ulysses#531]
*******************************************************
 NOTICE: ULX has been moved to a different repository!
 Please visit http://ulyssesmod.net/ for more details.
 Update your server as soon as possible!
*******************************************************

********************************************************
 NOTICE: ULib has been moved to a different repository!
 Please visit http://ulyssesmod.net/ for more details.
 Update your server as soon as possible!
********************************************************

Is it occuring, because I have everything installed in the folder "ulx"(ulib etc.)?

**Comment by 00875** [comment]
https://github.com/Nayruden/Ulysses/commit/69873b372dbde31080f31e2fd2b3659eab71ef60

**Comment by SticklyMan** [comment]
This is intentional. If you went to our website, you would have read our news post:
http://forums.ulyssesmod.net/index.php/topic,9111.0.html

Essentially, we're just moving the location of our GitHub repository and also splitting our projects into individual repositories. This repository will no longer be updated, so you'll want to switch to the new ones as soon as possible.
