### ISSUE TITLE
Applejack incompatibilities?

### ISSUE THREAD

**Issue by Nayruden** [Nayruden/Ulysses#7]
From the forum: http://forums.ulyssesmod.net/index.php/topic,5686.msg20822.html

There might be major breaking incompatibilities between ULX and Applejack. This is something worth looking into.

**Comment by SticklyMan** [comment]
Closing as we have not heard any further complaints. AppleJack still seems to be supported, and testing it on my test server seemed to work just fine.

**Comment by MichaelDeets** [comment]
Just tested with the latest release of AppleJack - https://github.com/Lexicality/applejack It is still incompatible.

**Comment by MichaelDeets** [comment]
Sorry to bug you about this, however it has been almost 3 years since it was known that ULX and Applejack do not go together. Dunno if it matters but in the latest release of applejack the effects are different - instead of spawning in "spectator mode" it now crashes the gamemode and results in the message "press jump to reconnect" on a black screen. Examples of some of the errors include "GM a nil value" on multiple different files.

Thank you for reading.
